### ISSUE TITLE
Unable to capture photo using Firefox

### ISSUE THREAD

**Issue by heyitshannes** [the-labo/the-cam#2]
When using Firefox, the cameara seems to be working just fine, but when trying to capture the input, I get the following error:
Error: ImageCapture not found!
In Chrome however, everything is running 100%.

**Comment by okunishinishi** [comment]
FF does not support ImageCapture  yet. 

This polyfill will fix the issue.

https://github.com/GoogleChromeLabs/imagecapture-polyfill#imagecapture-polyfill

**Comment by heyitshannes** [comment]
I just nopticed that the polyfill was added to the component. It is 100% working in FF now. Thank you. 👍
